### ISSUE TITLE
Feature request: Add date format yyyy-mm-dd

### ISSUE THREAD

**Issue by markalston** [andris9/mailtrain#132] opened 2017-02-02 13:59 UTC
On my initial import is was a bit frustrating to have to open my dump from my mysql database to convert the already international formatted YYYY-MM-DD dates into one of the two allowed by the mailtrain custom fields.  

Mailtrain is converting it back into mysql's standard date format anyway so it would be awesome to not have to convert it away in the first place.

**Comment by andris9** [comment] 2017-02-02 14:50
Fixed with 9778c486e99cffa3afe428c2358a8759b2a4fe19

Date processing is required as different date types use different semantics (eg DD/MM vs MM/DD). I changed it in a way that YYYY-MM-DD is tried first and if it does not match then try the normal approach.

**Closed by andris9** 2017-02-02 14:50 UTC

**Comment by markalston** [comment] 2017-02-03 02:55
So when setting up the custom field data it really doesn't matter which data type we pick if we are importing yyyy-mm-dd data?  If so, thats good.  But I still wonder why yyyy-mm-dd isn't a choice when setting up the custom fields in the first place.

**Comment by markalston** [comment] 2017-02-05 15:17
Am running into more problems with YYYY-MM-DD dates.  They are not being tried first when using the API.  My dates of 
```
curl -XPOST https://xxx.xxxx.xxxx/api/subscribe/SJVHbahPl?access_token=xxxxxxxxxxxxxxxxxxxxxxxxxx --data 'EMAIL=testing@xxxxxx.com&FIRST_NAME=MARK&LAST_NAME=ALSTON&MERGE_LAST_SALE_DATE=2017-01-30&MERGE_FIRST_SALE_DATE=1998-10-10&MERGE_CUSTOMER_NUMBER=123456789&REQUIRE_CONFIRMATION=no'

{"error":"ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2097-12-31 17:00:00.000' for column 'custom_last_sale_date_ryqewwpdg' at row 1","data":[]}
```
It would be really helpful to not have to convert date formats when the final dates are going to be stored in the exact same way I already have them anyway.

Please reopen this request.  I'll try to take a look at the code and see where the date choices are set but have no experience in node.js coding.

**Comment by andris9** [comment] 2017-02-05 15:23
How does the input value really looks like? How do you end up with this error?

**Comment by markalston** [comment] 2017-02-05 15:49
It looks exactly like that curl statement in my post above.  I have only obscured the api key and url. Everything else is exactly as shown.

 If I change the dates part of my curl command to:

```
LAST_SALE_DATE=01%2f30%2f2017&MERGE_FIRST_SALE_DATE=10%2f10%2f1998
```

The API insert works.
but with

```
MERGE_LAST_SALE_DATE=2017-01-30&MERGE_FIRST_SALE_DATE=1998-10-10
```

I get 

```
{"error":"ER_TRUNCATED_WRONG_VALUE: Incorrect datetime value: '2097-12-31 17:00:00.000' for column 'custom_last_sale_date_ryqewwpdg' at row 1","data":[]}
```

**Comment by andris9** [comment] 2017-02-05 18:04
Are you running the latest version of Mailtrain in the git, eg. the commit 9778c486e99cffa3afe428c2358a8759b2a4fe19 ? I can't reproduce this myself

```bash
$ curl -XPOST https://mailtrain.org/api/subscribe/Hkpbg6gux?access_token=zzzzzz --data 'EMAIL=test@kreata.ee&MERGE_KP=1998-10-10'
> {"data":{"id":"SkfNryHdl"}}
```

And the stored date is "10/10/1998"

**Comment by markalston** [comment] 2017-02-08 14:02
Oops, I wasn't. Coming from svn I thought that git status would actually 
tell me if I was updated.  I pulled the fixes and now international 
dates are working fine.

Thanks.
